project_id = "bpzedtifdjbfrojlkano"

[functions.market-analysis]
verify_jwt = false

[functions.trading-advisor]
verify_jwt = false

[functions.analyze-trading-psychology]
verify_jwt = false

[functions.live-market-data]
verify_jwt = false
